[versions]
# https://developer.android.com/studio/releases/build-tools.html#notes
buildTools = "35.0.0"
buildToolsPreview = "36.0.0-rc4"

minSdk = "21"

compileSdk = "35"
compileSdkPreview = "Baklava"

compileSdkExtension = "14" # 35-ext14

targetSdk = "35"
targetSdkPreview = "Baklava"

ndk = "28.0.13004108"
cmake = "3.31.5"

versionCode = "64"
versionName = "1.17.2_unpublished"

[libraries]

[bundles]

[plugins]